---
# file: /roles/cassandra/tasks/main.yml

##########################################################
# Create required directories

- name: "Create result dir: ../results/"
  file: >
    path={{ result_dir }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: "Create workload dir: ../workloads/fio"
  file: >
    path={{ workload_dir }}
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: Install fio via apt
  sudo: true
  apt: name=fio state=present

- name: "Create workload executor script: start_wl.sh"
  template: >
    src=start_wl.j2
    dest="{{ workload_dir }}/start_wl.sh"
    owner={{ user }}
    group={{ user }}
    mode=0777

- name: "Create worklaod file: wl.job"
  template: >
    src="{{ exe_wl_template }}.j2"
    dest="{{ workload_dir }}/wl.job"
    owner={{ user }}
    group={{ user }}
    mode=0777
    
- name: "Create inv dir: ../workloads/inv"
  file: >
    path={{ workload_dir }}/inv
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0775"

- name: "Create localhost file: hosts"
  template: >
    src=hosts.j2
    dest="{{ workload_dir }}/inv/hosts"
    owner={{ user }}
    group={{ user }}
    mode=0664

- name: "Install package: python-pip"
  sudo: true
  apt: name=python-pip state=present

- name: "Install package: boto"
  sudo: true
  pip: name=boto state=latest

- name: "Install package: awscli"
  sudo: true
  pip: name=awscli state=latest

- name: "Install package: ansible"
  sudo: true
  apt: name=ansible state=latest

- name: "Create config dir: ../.aws/"
  file: >
    path="{{ home_dir }}/.aws"
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
    mode="0755"

- name: "Create AWS CLI config file: ../.aws/config"
  template: >
    src="awscli_config.j2"
    dest="{{ home_dir }}/.aws/config"
    owner={{ user }}
    group={{ user }}
    mode=0600

- name: "Export AWS_CONFIG_FILE in ../.bashrc"
  lineinfile: >
    dest=/home/ubuntu/.bashrc
    line="export AWS_CONFIG_FILE={{ home_dir }}//.aws/config"
